## =============================================================================
## SUPERSEDED 2026-07-29 — use the misspecification cells in
## 06_simulation_redesign.R (scen_id 3-7) for Section 5.3 instead.
##
## Why this script should not be run:
##  1. fit_one() and mod_int are defined in 04_simulation_study.R, which this
##     file never sources. Because the call is wrapped in tryCatch(...) the
##     resulting "object 'fit_one' not found" is swallowed into conv = 0L for
##     every replicate, producing a fully populated table of NAs with no error.
##     Sourcing 02_fit_models.R also fires two full HMC fits as a side effect.
##  2. fit_one() estimates by $optimize() — see the deprecation note at the top
##     of 04_simulation_study.R. Setting USE_MCMC <- TRUE here has no effect on
##     adapt_delta (ADAPT = 0.99 below is never used; fit_one hardcodes 0.95).
##  3. The threshold_m5 cell is inert. build_stan_interval() re-derives events
##     from the GLOBAL C_D = -4.5 and ignores coh$pat entirely, so the scenario's
##     cD = -5.0 changes only the Brier target, not the likelihood. And since
##     C_F = -5.0, a threshold at -5.0 makes detection identical to the assay
##     floor indicator.
##  4. Events here are generated by deterministic crossing of the observed y, so
##     alpha and gamma0..2 have no generative value — yet 95% "credible-interval
##     coverage of alpha_MRD" is the headline column of tab:sim-misspec.
##  5. Coverage uses est +/- 1.96*se, a Wald approximation, not posterior
##     quantiles; for log_sigma/log_tau1 it is delta-method on top of that.
##  6. cal_slope is never returned by fit_one(), so agg$cal_slope is NaN.
##
## The interval-hazard vs deterministic-threshold question in (4) is a real
## modelling decision, not a bug; dgm_common.R now exposes it as
## EVENT_MECHANISM so it can be chosen explicitly and reported.
## =============================================================================

## 12_misspecification_study.R ---------------------------------------------
## Fills Section 5.3 ("Robustness to misspecification") of the manuscript.
##
## DESIGN. Data are generated under a departure from the working model; the
## WORKING model (piecewise-quadratic trajectory, Gaussian errors, single assay
## floor, schedule-conditional) is then fitted unchanged. Everything reported is
## therefore the cost of fitting the working model when it is wrong.
##
## SCENARIOS (one departure at a time, n = 150)
##   correct        reference: data from the working model
##   traj_monotone  smoother monotone decline (no quadratic upturn)
##   traj_exp       sharper exponential approach to an asymptote
##   threshold_m5   DMR threshold at -5.0 instead of -4.5
##   hetero_floor   patient-specific assay floors
##   heavy_t3       t3 measurement errors AND t3 random effects
##   informative    response-adaptive visit intensity
##
## OUTPUT
##   outputs/misspec_raw.csv      one row per replicate
##   outputs/misspec_summary.csv  bias / coverage / calibration + MCse
##   outputs/table_misspec.tex    LaTeX table for Section 5.3
##
## RUNTIME. USE_MCMC = TRUE is required for honest credible-interval coverage
## and is the slow path (~4 chains x 7 scenarios x N_REP fits). Start with
## N_REP = 5 and USE_MCMC = FALSE to verify the pipeline, then scale up.
## -------------------------------------------------------------------------

source(file.path(dirname(sys.frame(1)$ofile %||% "."), "00_setup.R"))
source(file.path(dirname(sys.frame(1)$ofile %||% "."), "01_simulate_data.R"))
source(file.path(dirname(sys.frame(1)$ofile %||% "."), "02_fit_models.R"))

N_REP    <- 200      # manuscript target; use 5-10 for a smoke test
N_SIM    <- 150      # n per scenario, as stated in Section 5.3
USE_MCMC <- TRUE     # FALSE = fast MAP (no coverage); TRUE = HMC (coverage)
ADAPT    <- 0.99

## ---- 1. generators for each departure ------------------------------------
## Each returns a latent-trajectory function m(t, u0, u1); the fitted model
## always assumes the quadratic form, so any other shape is a misspecification.
traj_fun <- function(scen, p = TRUTH) {
  switch(scen,
    ## working model: beta0 + beta1*l + beta2*l^2
    correct = function(t, u0, u1) p$beta0 + p$beta1*ell(t) + p$beta2*ell(t)^2 + u0 + u1*ell(t),
    ## monotone decline: quadratic term removed, slope steepened to match depth
    traj_monotone = function(t, u0, u1) p$beta0 + (p$beta1 + 0.45)*ell(t) + u0 + u1*ell(t),
    ## exponential approach to an asymptote (sharper early decline, hard floor)
    traj_exp = function(t, u0, u1) {
      asy <- p$beta0 + p$beta1*1.6
      (p$beta0 - asy) * exp(-1.8 * t) + asy + u0 + u1*ell(t)
    },
    ## remaining scenarios keep the correct trajectory
    function(t, u0, u1) p$beta0 + p$beta1*ell(t) + p$beta2*ell(t)^2 + u0 + u1*ell(t)
  )
}

## heavy-tailed draws, scaled to the same SD as the Gaussian case
rt_scaled <- function(n, sd, df = 3) sd * rt(n, df) / sqrt(df/(df-2))

simulate_misspec <- function(scen, n, seed, p = TRUTH, p_bm = 0.90) {
  set.seed(seed)
  m_fun <- traj_fun(scen, p)
  cD    <- if (scen == "threshold_m5") -5.0 else C_D
  heavy <- scen == "heavy_t3"
  informative <- scen == "informative"

  long <- list(); pat <- vector("list", n)
  for (i in seq_len(n)) {
    ## random effects: Gaussian, or t3 under the heavy-tailed departure
    if (heavy) { u0 <- rt_scaled(1, p$tau0); u1 <- rt_scaled(1, p$tau1) }
    else       { u0 <- rnorm(1, 0, p$tau0);  u1 <- rnorm(1, 0, p$tau1) }
    Ci <- runif(1, 1.5, 7.0)

    ## patient-specific floor under the heterogeneous-floor departure
    cF_i <- if (scen == "hetero_floor") C_F + rnorm(1, 0, 0.35) else C_F

    ## visit times (reuse the informative-intensity scheme from 01_simulate_data.R)
    if (!informative) {
      t <- numeric(0); cur <- 0
      repeat { cur <- cur + rlnorm(1, log(0.55), 0.5); if (cur > Ci) break; t <- c(t, cur) }
    } else {
      w <- rnorm(1, 0, 0.5); d0 <- -0.7; d1 <- 0.35; d2 <- 0.2
      grid <- seq(1e-3, Ci, length.out = 50)
      lam_max <- max(exp(d0 + d1*(m_fun(grid,u0,u1)+4.5) + d2*ell(grid) + w))*1.2 + 1e-6
      t <- numeric(0); cur <- 0
      repeat {
        cur <- cur + rexp(1, lam_max); if (cur > Ci) break
        lam <- exp(d0 + d1*(m_fun(cur,u0,u1)+4.5) + d2*ell(cur) + w)
        if (runif(1) < lam/lam_max) t <- c(t, cur)
      }
    }
    if (length(t) == 0 || min(t) > 0.25) t <- c(runif(1, 0.02, 0.12), t)
    t <- sort(t)

    bm <- rbinom(length(t), 1, p_bm)
    mu <- m_fun(t, u0, u1) + p$beta_bm * bm
    ys <- if (heavy) mu + rt_scaled(length(t), p$sigma_y) else rnorm(length(t), mu, p$sigma_y)
    fl <- as.integer(ys <= cF_i)
    yobs <- ifelse(fl == 1, C_F, ys)   # lab always REPORTS the nominal floor

    dv <- which(yobs <= cD); delta <- as.integer(length(dv) > 0)
    edges <- c(0, t)
    if (delta == 1) { k <- dv[1]; L <- edges[k]; R <- edges[k+1] } else { L <- NA; R <- NA }

    long[[i]] <- data.frame(pid = i, t = t, ell = ell(t), y = yobs, floor = fl, bm = bm)
    pat[[i]]  <- data.frame(pid = i, delta = delta, L = L, R = R, Cend = Ci)
  }
  list(long = do.call(rbind, long), pat = do.call(rbind, pat), n = n)
}

## ---- 2. run ---------------------------------------------------------------
SCEN <- c("correct","traj_monotone","traj_exp","threshold_m5",
          "hetero_floor","heavy_t3","informative")
PARS <- c("alpha","b1","log_sigma","log_tau1")   # reported in Section 5.3
truth <- c(alpha = TRUTH$alpha, b1 = TRUTH$beta1,
           log_sigma = log(TRUTH$sigma_y), log_tau1 = log(TRUTH$tau1))

## fit_one() returns the Stan parameter names on their natural scales, whereas
## this study reports the time slope as b1 and the two SDs on the log scale.
## Extract with `[` (not `[[`) only after checking the name so a failed or
## incompatible fit becomes NA instead of raising "subscript out of bounds".
fit_reported_parameter <- function(fit, pn) {
  native_name <- c(alpha = "alpha", b1 = "beta1",
                   log_sigma = "sigma_y", log_tau1 = "tau1")[[pn]]
  get_named_number <- function(x, nm) {
    if (is.null(x) || is.null(names(x)) || !nm %in% names(x)) return(NA_real_)
    value <- unname(x[nm])
    if (length(value) != 1L || !is.numeric(value)) return(NA_real_)
    as.numeric(value)
  }

  est <- get_named_number(fit$est, native_name)
  se  <- get_named_number(fit$se, native_name)
  if (pn %in% c("log_sigma", "log_tau1")) {
    ## Delta-method SE on the log scale. MAP fits already return NA SEs.
    if (!is.finite(est) || est <= 0) return(c(est = NA_real_, se = NA_real_))
    se  <- if (is.finite(se)) se / est else NA_real_
    est <- log(est)
  }
  c(est = est, se = se)
}

res <- list(); row <- 0
for (sc in SCEN) {
  for (r in seq_len(N_REP)) {
    coh <- simulate_misspec(sc, N_SIM, seed = 7000 + 1000*match(sc, SCEN) + r)
    ## fit_one() is defined in 04_simulation_study.R / 02_fit_models.R and fits
    ## the WORKING model; USE_MCMC controls MAP vs HMC.
    fit <- tryCatch(fit_one(coh, exact = FALSE), error = function(e) NULL)
    row <- row + 1
    if (is.null(fit)) { res[[row]] <- data.frame(scen = sc, rep = r, conv = 0L); next }
    d <- data.frame(scen = sc, rep = r, conv = 1L,
                    brier = fit$brier %||% NA, cal_slope = fit$cal_slope %||% NA)
    for (pn in PARS) {
      stat <- fit_reported_parameter(fit, pn)
      est <- stat[["est"]]; se <- stat[["se"]]
      d[[paste0("est_", pn)]] <- est
      d[[paste0("cov_", pn)]] <- as.integer(!is.na(est) && !is.na(se) &&
                                  abs(est - truth[[pn]]) <= 1.96*se)
    }
    res[[row]] <- d
  }
  message("done: ", sc)
}
res <- do.call(plyr::rbind.fill, res)
write.csv(res, file.path(DIR_OUT, "misspec_raw.csv"), row.names = FALSE)

## ---- 3. aggregate with Monte Carlo standard errors ------------------------
mcse_prop <- function(x) { x <- x[!is.na(x)]; sqrt(mean(x)*(1-mean(x))/length(x)) }
agg <- do.call(rbind, lapply(split(res, res$scen), function(d) {
  k <- sum(d$conv == 1)
  out <- data.frame(scenario = d$scen[1], nrep = nrow(d), converged = k,
                    conv_rate = round(k/nrow(d), 3))
  for (pn in PARS) {
    e <- d[[paste0("est_", pn)]]; cv <- d[[paste0("cov_", pn)]]
    out[[paste0("bias_", pn)]]  <- round(mean(e, na.rm = TRUE) - truth[[pn]], 3)
    out[[paste0("mcse_", pn)]]  <- round(sd(e, na.rm = TRUE)/sqrt(sum(!is.na(e))), 3)
    out[[paste0("cov_", pn)]]   <- round(mean(cv, na.rm = TRUE), 3)
    out[[paste0("covmc_", pn)]] <- round(mcse_prop(cv), 3)
  }
  out$cal_slope <- round(mean(d$cal_slope, na.rm = TRUE), 3)
  out
}))
agg <- agg[match(SCEN, agg$scenario), ]
write.csv(agg, file.path(DIR_OUT, "misspec_summary.csv"), row.names = FALSE)
print(agg[, c("scenario","conv_rate","bias_alpha","cov_alpha","cov_b1","cov_log_sigma","cov_log_tau1")])

## ---- 4. LaTeX table for Section 5.3 --------------------------------------
lab <- c(correct="Correct specification", traj_monotone="Trajectory: monotone",
         traj_exp="Trajectory: exponential", threshold_m5="Threshold at $-5.0$",
         hetero_floor="Heterogeneous assay floor", heavy_t3="Heavy-tailed ($t_3$) errors/RE",
         informative="Informative monitoring")
con <- file(file.path(DIR_OUT, "table_misspec.tex"), "w")
writeLines(c(
"\\begin{table}[!htbp]","\\centering",
"\\caption{Robustness of the Hamiltonian Monte Carlo estimator to misspecification:",
" $95\\%$ credible-interval coverage of the association $\\alpha_{\\mathrm{MRD}}$, the time",
" slope $\\beta_{\\mathrm{time}}$, the residual SD $\\sigma_y$ and the random-slope SD",
" $\\tau_{b1}$, under one departure at a time ($n=150$). Monte Carlo standard errors for",
" coverage are in parentheses; the final column is the proportion of fits meeting all",
" diagnostic thresholds.}",
"\\label{tab:sim-misspec}","\\small",
"\\begin{tabular}{lccccc}","\\toprule",
"Scenario & $\\alpha_{\\mathrm{MRD}}$ & $\\beta_{\\mathrm{time}}$ & $\\sigma_y$ & $\\tau_{b1}$ & Converged\\\\",
"\\midrule"), con)
for (i in seq_len(nrow(agg))) with(agg[i,], writeLines(sprintf(
  "%s & %.2f (%.2f) & %.2f (%.2f) & %.2f (%.2f) & %.2f (%.2f) & %.2f\\\\",
  lab[[scenario]], cov_alpha, covmc_alpha, cov_b1, covmc_b1,
  cov_log_sigma, covmc_log_sigma, cov_log_tau1, covmc_log_tau1, conv_rate), con))
writeLines(c("\\bottomrule","\\end{tabular}","\\end{table}"), con); close(con)
message("\nWrote outputs/table_misspec.tex — \\input this into Section 5.3.")
