## =============================================================================
## 15_prior_sensitivity.R  —  how much of the inference is prior, not data?
##
## MOTIVATION. The v2_cohort simulation study (06) shows bias in exactly the
## parameters whose true values sit far in the tails of the fixed priors, and
## every bias points at its prior mean:
##
##   param    truth    prior         bias n=87   bias n=300   coverage n=300
##   gamma2   -2.325   N(0, 1)         +1.069       +0.551          0.818
##   beta1    -3.234   N(-1, 1)        +0.673       +0.247          0.922
##   beta2     0.455   N(0, 0.5)       -0.318       -0.116          0.935
##   alpha    -1.774   N(-0.5, 0.75)   +0.278       +0.134          0.909
##
## gamma2 is the problem: its coverage does not recover as n grows (0.754,
## 0.814, 0.818 at n = 87, 150, 300). That is the signature of a prior fighting
## the data, not of a finite-sample effect, and it is the objection a referee is
## most likely to raise. It is also fixable by widening a prior rather than by
## changing the model.
##
## WHAT THIS DOES
##   (A) refits the SAME dataset under several prior sets and reports how far
##       each posterior moves -- the actual sensitivity;
##   (B) quantifies prior-data conflict as |posterior mean - prior mean| / prior
##       SD, and prior influence as posterior SD / prior SD;
##   (C) optionally (PRIOR_SIM=1) re-runs a small simulation cell under each
##       prior set to test whether widening restores coverage. This is the
##       decisive evidence and the slow path.
##
## !! DATA PROVENANCE !!
## This folder is a simulation-only methods sandbox. The dataset fitted here is
## SYNTHETIC -- generated by dgm_common.R at the configured mechanism, not the
## CML cohort (which lives in 03_Data/Processed and is analysed by 04_Code/R).
## Report these results as a prior sensitivity analysis for the simulation
## study. To make the same argument about the APPLICATION, the analysis must be
## repeated inside the 04_Code/R pipeline on the real data.
##
## RUN (from the R/ folder):
##   Rscript 15_prior_sensitivity.R              # refit one dataset, ~5 fits
##   $env:PRIOR_SIM=1; Rscript 15_prior_sensitivity.R   # + coverage arm (slow)
## =============================================================================
suppressMessages({ library(cmdstanr); library(posterior) })

.ps_dir <- local({
  a <- commandArgs(FALSE); m <- grep("^--file=", a, value = TRUE)
  if (length(m)) dirname(normalizePath(sub("^--file=", "", m[1])))
  else tryCatch(dirname(normalizePath(sys.frame(1)$ofile)), error = function(e) getwd())
})
source(file.path(.ps_dir, "dgm_common.R"))
dgm_describe()

CFG <- list(
  n = 150L, seed = 20260730L,
  chains = 4L, parallel_chains = 4L, iter_warmup = 600L, iter_sampling = 800L,
  adapt_delta = 0.95, max_treedepth = 11L,
  sim_reps = as.integer(Sys.getenv("PRIOR_SIM_REPS", "40")),
  out_dir = file.path(.ps_dir, "..", "outputs", "prior_sensitivity"))
dir.create(CFG$out_dir, recursive = TRUE, showWarnings = FALSE)
STAN <- normalizePath(file.path(.ps_dir, "..", "stan", "interval_hazard_joint_pp.stan"))

## ---- prior sets -------------------------------------------------------------
## "current" reproduces interval_hazard_joint.stan exactly. The others widen the
## scales only; locations are left alone so the comparison isolates the effect of
## prior INFORMATIVENESS rather than of moving the prior toward the answer
## (which would beg the question).
base_prior <- list(
  pr_beta0 = c(-2.5, 2), pr_beta1 = c(-1, 1), pr_beta2 = c(0, 0.5),
  pr_beta_bm = c(0, 1), pr_sigma_y = 1, pr_tau0 = 1, pr_tau1 = 1,
  pr_gamma0 = c(-2, 2), pr_gamma1 = c(0, 1), pr_gamma2 = c(0, 1),
  pr_alpha = c(-0.5, 0.75))

widen <- function(p, k, which_ = c("pr_beta1","pr_beta2","pr_gamma0","pr_gamma1",
                                   "pr_gamma2","pr_alpha")) {
  for (nm in which_) p[[nm]][2] <- p[[nm]][2] * k
  p
}
PRIORS <- list(
  current   = base_prior,                    # as published
  wide2     = widen(base_prior, 2),          # 2x scale on regression/hazard terms
  wide4     = widen(base_prior, 4),          # 4x
  vague     = { p <- widen(base_prior, 10)   # near-flat on the scale of the data
                p$pr_sigma_y <- 0.5; p$pr_tau0 <- 0.5; p$pr_tau1 <- 0.5; p })

## ---- one synthetic dataset, fitted under every prior set --------------------
CENTRAL <- list(trajectory = "quadratic", floor_kind = "fixed",
                err_family = "gaussian", re_family = "gaussian", informative = FALSE)
set.seed(CFG$seed)
ds   <- simulate_dataset(CFG$n, CENTRAL)
sdat <- make_stan_data(ds)
mod  <- cmdstan_model(STAN)

## gq = 0 suppresses the per-observation / per-interval posterior-predictive
## quantities. With them on, a single n=150 fit writes ~43 MB PER CHAIN (about
## 4,650 columns x 800 draws) which is then parsed back into R -- and this script
## uses only the 11 scalar parameters. Only `variables` are pulled from the CSVs.
fit_with <- function(pr, prior_only = 0L, standata = sdat, gq = 0L) {
  d <- c(standata, pr, list(prior_only = prior_only, gq = gq))
  f <- mod$sample(data = d, chains = CFG$chains, parallel_chains = CFG$parallel_chains,
                  iter_warmup = CFG$iter_warmup, iter_sampling = CFG$iter_sampling,
                  adapt_delta = CFG$adapt_delta, max_treedepth = CFG$max_treedepth,
                  refresh = 0, show_messages = FALSE, show_exceptions = FALSE)
  f$draws(variables = PARAMS, format = "draws_df")
}

## prior location/scale for a parameter, on its own scale
prior_moments <- function(pr, p) {
  key <- paste0("pr_", p)
  v <- pr[[key]]
  if (p %in% c("sigma_y","tau0","tau1")) c(mean = 1/v, sd = 1/v)  # exponential(rate)
  else c(mean = v[1], sd = v[2])
}

rows <- list()
for (nm in names(PRIORS)) {
  message("fitting prior set: ", nm)
  dr <- fit_with(PRIORS[[nm]])
  rh <- max(summarise_draws(dr, "rhat")$rhat, na.rm = TRUE)
  for (p in PARAMS) {
    x  <- as.numeric(dr[[p]]); pm <- prior_moments(PRIORS[[nm]], p)
    qi <- quantile(x, c(0.025, 0.975))
    rows[[length(rows) + 1]] <- data.frame(
      prior_set = nm, param = p,
      prior_mean = pm[["mean"]], prior_sd = pm[["sd"]],
      post_mean = mean(x), post_sd = sd(x), q2.5 = qi[1], q97.5 = qi[2],
      truth = TRUTH[[p]],
      bias = mean(x) - TRUTH[[p]],
      covered = as.integer(TRUTH[[p]] >= qi[1] & TRUTH[[p]] <= qi[2]),
      ## how far the data drag the posterior into the prior's tail
      conflict_sd = abs(mean(x) - pm[["mean"]]) / pm[["sd"]],
      ## how much of the posterior width is still prior: ~1 means no learning
      sd_ratio = sd(x) / pm[["sd"]],
      max_rhat = rh, row.names = NULL)
  }
}
res <- do.call(rbind, rows)
write.csv(res, file.path(CFG$out_dir, "prior_sensitivity_refits.csv"), row.names = FALSE)

## ---- report -----------------------------------------------------------------
key <- c("gamma2","beta1","alpha","beta2","sigma_y","tau1")
cat("\n=== posterior mean (95% CI) by prior set -- SYNTHETIC data, n =", CFG$n, "===\n")
cat(sprintf("%-9s %9s %s\n", "param", "truth",
            paste(sprintf("%-26s", names(PRIORS)), collapse = "")))
for (p in key) {
  cells <- vapply(names(PRIORS), function(nm) {
    r <- res[res$prior_set == nm & res$param == p, ]
    sprintf("%-26s", sprintf("%.3f (%.2f,%.2f)%s", r$post_mean, r$q2.5, r$q97.5,
                             if (r$covered == 1) "" else "*"))
  }, character(1))
  cat(sprintf("%-9s %9.3f %s\n", p, TRUTH[[p]], paste(cells, collapse = "")))
}
cat("* = 95% CI excludes the data-generating value\n")

cat("\n=== prior-data conflict, current priors ===\n")
cat(sprintf("%-9s %10s %10s %12s %10s\n", "param", "prior_mean", "post_mean",
            "conflict_sd", "sd_ratio"))
cur <- res[res$prior_set == "current", ]
cur <- cur[order(-cur$conflict_sd), ]
for (i in seq_len(nrow(cur))) with(cur[i, ],
  cat(sprintf("%-9s %10.3f %10.3f %12.2f %10.2f%s\n", param, prior_mean, post_mean,
              conflict_sd, sd_ratio, if (conflict_sd > 1.5) "  <-- conflict" else "")))
cat("conflict_sd = |post mean - prior mean| / prior SD; >1.5 means the data are\n")
cat("pulling well into the prior's tail, so the prior is materially informative.\n")

## ---- (C) optional: does widening restore coverage? --------------------------
if (Sys.getenv("PRIOR_SIM", "0") == "1") {
  ## CHECKPOINTED per fit, like 06_simulation_redesign.R. Without this the arm
  ## wrote nothing until all reps finished: progress was unobservable and a crash
  ## at the last fit destroyed every preceding one. Re-running resumes.
  CKPT <- file.path(CFG$out_dir, paste0("checkpoints_", dgm_tag()))
  dir.create(CKPT, recursive = TRUE, showWarnings = FALSE)
  ntot <- length(PRIORS) * CFG$sim_reps
  message("\ncoverage arm: ", CFG$sim_reps, " reps x ", length(PRIORS),
          " prior sets = ", ntot, " fits")
  message("checkpoints: ", CKPT)
  for (nm in names(PRIORS)) {
    for (r in seq_len(CFG$sim_reps)) {
      id <- sprintf("%s_r%03d", nm, r); f_ck <- file.path(CKPT, paste0(id, ".rds"))
      if (file.exists(f_ck)) next
      set.seed(CFG$seed + 1000 * match(nm, names(PRIORS)) + r)
      d2 <- simulate_dataset(CFG$n, CENTRAL)
      out <- tryCatch({
        dd <- fit_with(PRIORS[[nm]], standata = make_stan_data(d2))
        do.call(rbind, lapply(PARAMS, function(p) {
          x <- as.numeric(dd[[p]]); qi <- quantile(x, c(0.025, 0.975))
          data.frame(prior_set = nm, rep = r, param = p,
                     post_mean = mean(x),
                     bias = mean(x) - TRUTH[[p]],
                     ci_width = as.numeric(diff(qi)),
                     covered = as.integer(TRUTH[[p]] >= qi[1] & TRUTH[[p]] <= qi[2]))
        }))
      }, error = function(e)
        data.frame(prior_set = nm, rep = r, param = NA, post_mean = NA,
                   bias = NA, ci_width = NA, covered = NA))
      saveRDS(out, f_ck)
      ndone <- length(list.files(CKPT, pattern = "\\.rds$"))
      if (r %% 5 == 0) message(sprintf("  %-8s %3d/%3d   [%3d/%3d total]",
                                       nm, r, CFG$sim_reps, ndone, ntot))
    }
  }
  cv <- do.call(rbind, lapply(list.files(CKPT, pattern = "\\.rds$", full.names = TRUE),
                              readRDS))
  cv <- cv[!is.na(cv$param), ]
  write.csv(cv, file.path(CFG$out_dir, "prior_sensitivity_coverage_raw.csv"), row.names = FALSE)
  ag <- do.call(rbind, lapply(split(cv, list(cv$prior_set, cv$param), drop = TRUE), function(d) {
    n <- nrow(d); cc <- mean(d$covered)
    data.frame(prior_set = d$prior_set[1], param = d$param[1], nrep = n,
               bias = mean(d$bias), bias_mcse = sd(d$bias)/sqrt(n),
               coverage = cc, cov_mcse = sqrt(cc*(1-cc)/n), row.names = NULL) }))
  write.csv(ag, file.path(CFG$out_dir, "prior_sensitivity_coverage.csv"), row.names = FALSE)
  cat("\n=== coverage by prior set (n =", CFG$n, ", ", CFG$sim_reps, "reps) ===\n")
  cat(sprintf("%-9s %s\n", "param", paste(sprintf("%-16s", names(PRIORS)), collapse = "")))
  for (p in key) {
    cells <- vapply(names(PRIORS), function(nm) {
      r <- ag[ag$prior_set == nm & ag$param == p, ]
      if (!nrow(r)) return(sprintf("%-16s", "---"))
      sprintf("%-16s", sprintf("%.3f (%.3f)", r$coverage, r$cov_mcse))
    }, character(1))
    cat(sprintf("%-9s %s\n", p, paste(cells, collapse = "")))
  }
}

message("\nOutputs -> ", CFG$out_dir)
message("NOTE: fitted to SYNTHETIC data. Repeat inside 04_Code/R for the application.")
