## =============================================================================
## 17_calibration_study.R  —  patient-level DMR calibration (regenerates Table 12)
## and the FIRST simulation of the latent threshold-crossing model.
##
## WHY. Table 12 (tab:sim-calibration) currently supplies two things it should
## not. (i) Its "Informative / floor" row -- the source of the calibration slope
## quoted in the Discussion -- was generated by a visit mechanism that duplicated
## ~30% of visit times INDEPENDENTLY of the latent trajectory. That is not
## informative monitoring; it produced duplicate visit times and zero-length
## at-risk intervals, and it tested nothing. (ii) Its "threshold (n=150)" row is
## the only simulation anywhere in the paper of the latent threshold-crossing
## model -- the formulation presented as the more novel contribution -- at 40
## replicates from a superseded pipeline, while that model carries 219 divergent
## transitions on the cohort fit.
##
## This script regenerates both under the current mechanism, with the corrected
## non-homogeneous Poisson visit process from dgm_common.R.
##
## CELLS
##   floor      n = 87, 150, 300   non-informative monitoring
##   floor      n = 150            informative monitoring (NHPP on latent MRD)
##   threshold  n = 150            non-informative monitoring
##
## MEASURES (patient level, predicted P(documented DMR by end of follow-up))
##   Brier score; calibration intercept and slope from the logistic regression
##   of the observed indicator on logit(predicted); mean predicted; observed rate.
##   Divergent transitions are recorded per fit -- for the threshold arm this is
##   the quantity of interest in its own right.
##
## RUN (from the R/ folder)
##   $env:QUICK_TEST=1; Rscript 17_calibration_study.R
##   ./run_shards_calib.ps1
## =============================================================================
suppressMessages({ library(cmdstanr); library(posterior) })

.cal_dir <- local({
  a <- commandArgs(FALSE); m <- grep("^--file=", a, value = TRUE)
  if (length(m)) dirname(normalizePath(sub("^--file=", "", m[1])))
  else tryCatch(dirname(normalizePath(sys.frame(1)$ofile)), error = function(e) getwd())
})
source(file.path(.cal_dir, "dgm_common.R"))
dgm_describe()

N_SHARDS <- as.integer(Sys.getenv("N_SHARDS", "1"))
SHARD_ID <- as.integer(Sys.getenv("SHARD_ID", "0"))
CFG <- list(
  TIME_BUDGET_HOURS = 10,
  n_rep = as.integer(Sys.getenv("N_REP_CALIB", "100")),
  chains = 4L, parallel_chains = 4L,
  iter_warmup = 600L, iter_sampling = 500L,
  adapt_delta = 0.95, max_treedepth = 11L,
  G = 60L, KAPPA = 50, seed = 20260801L,
  out_dir = file.path(.cal_dir, "..", "outputs", "calibration"))
CFG$ckpt_dir <- file.path(CFG$out_dir, paste0("checkpoints_", dgm_tag()))
dir.create(CFG$ckpt_dir, recursive = TRUE, showWarnings = FALSE)
if (Sys.getenv("QUICK_TEST", "0") == "1") {
  CFG$n_rep <- 2L
  if (N_SHARDS != 1L || SHARD_ID != 0L)
    message(sprintf("QUICK_TEST: ignoring inherited N_SHARDS=%d SHARD_ID=%d.", N_SHARDS, SHARD_ID))
  N_SHARDS <- 1L; SHARD_ID <- 0L
  message("QUICK_TEST: 2 reps.")
}

STAN_INT <- normalizePath(file.path(.cal_dir, "..", "stan", "interval_hazard_joint_pp.stan"))
STAN_THR <- normalizePath(file.path(.cal_dir, "..", "stan", "threshold_crossing_joint.stan"))
mod_int <- cmdstan_model(STAN_INT)
mod_thr <- cmdstan_model(STAN_THR)

## ---- per-patient event summary from the interval representation -------------
## dgm_common returns long + at-risk intervals; the threshold model needs one
## row per patient with (delta, L, R, Cend).
patient_frame <- function(ds) {
  iv <- ds$intervals
  do.call(rbind, lapply(sort(unique(iv$pid)), function(i) {
    d <- iv[iv$pid == i, ]
    k <- which(d$event == 1)[1]
    Cend <- max(ds$long$t[ds$long$pid == i])
    if (is.na(k)) data.frame(pid = i, delta = 0L, L = NA_real_, R = NA_real_, Cend = Cend)
    else          data.frame(pid = i, delta = 1L, L = d$t_start[k], R = d$t_end[k], Cend = Cend)
  }))
}

make_thr_data <- function(ds, pat, G = CFG$G, kappa = CFG$KAPPA) {
  N <- nrow(pat); ellf <- function(x) log1p(x)
  ellA <- ellB <- ellC <- matrix(0, N, G)
  for (i in seq_len(N)) {
    if (pat$delta[i] == 1) {
      ellA[i, ] <- ellf(seq(0, pat$L[i], length.out = G))
      ellB[i, ] <- ellf(seq(0, pat$R[i], length.out = G))
    } else {
      ellA[i, ] <- ellf(seq(0, pat$Cend[i], length.out = G)); ellB[i, ] <- ellA[i, ]
    }
    ellC[i, ] <- ellf(seq(0, pat$Cend[i], length.out = G))
  }
  list(N = N, Nobs = nrow(ds$long), pid = ds$long$pid, ell = ds$long$ell,
       y = ds$long$y, floor_ind = ds$long$floor_ind, bm = ds$long$bm,
       cF = FLOOR, cD = C_D, delta = pat$delta, G = G,
       ellA = ellA, ellB = ellB, ellC = ellC, kappa = kappa)
}

## ---- calibration measures ---------------------------------------------------
calib <- function(p, y) {
  p <- pmin(pmax(p, 1e-6), 1 - 1e-6)
  lp <- qlogis(p)
  fit <- tryCatch(glm(y ~ lp, family = binomial()), error = function(e) NULL)
  co <- if (is.null(fit)) c(NA_real_, NA_real_) else unname(coef(fit))
  data.frame(brier = mean((p - y)^2), cal_int = co[1], cal_slope = co[2],
             mean_pred = mean(p), obs_rate = mean(y))
}

## ---- queue ------------------------------------------------------------------
cells <- rbind(
  data.frame(model = "floor",     n = 87L,  informative = FALSE),
  data.frame(model = "floor",     n = 150L, informative = FALSE),
  data.frame(model = "floor",     n = 300L, informative = FALSE),
  data.frame(model = "floor",     n = 150L, informative = TRUE),
  data.frame(model = "threshold", n = 150L, informative = FALSE))
cells$cell_id <- seq_len(nrow(cells))
queue <- do.call(rbind, lapply(seq_len(nrow(cells)), function(s)
  cbind(cells[rep(s, CFG$n_rep), ], rep = seq_len(CFG$n_rep), row.names = NULL)))
queue$task_id <- sprintf("c%d_%s_n%d_%s_r%03d", queue$cell_id, queue$model, queue$n,
                         ifelse(queue$informative, "inf", "ni"), queue$rep)
queue <- queue[order(queue$cell_id, queue$rep), ]
queue$shard <- (seq_len(nrow(queue)) - 1L) %% N_SHARDS
done <- sub("\\.rds$", "", list.files(CFG$ckpt_dir, pattern = "\\.rds$"))
todo <- queue[queue$shard == SHARD_ID & !(queue$task_id %in% done), ]
message(sprintf("Queue %d | shard %d has %d | %d remaining.", nrow(queue),
                SHARD_ID, sum(queue$shard == SHARD_ID), nrow(todo)))

## ---- main loop --------------------------------------------------------------
start <- Sys.time(); ndone <- 0L
for (i in seq_len(nrow(todo))) {
  if (as.numeric(difftime(Sys.time(), start, units = "hours")) > CFG$TIME_BUDGET_HOURS) {
    message("Time budget reached; re-run to resume."); break }
  tk <- as.list(todo[i, ]); f <- file.path(CFG$ckpt_dir, paste0(tk$task_id, ".rds"))
  if (file.exists(f)) next
  set.seed(CFG$seed + 1000L * tk$cell_id + tk$rep)
  out <- tryCatch({
    scen <- list(trajectory = "quadratic", floor_kind = "fixed",
                 err_family = "gaussian", re_family = "gaussian",
                 informative = tk$informative)
    ds  <- simulate_dataset(tk$n, scen)
    pat <- patient_frame(ds)

    if (tk$model == "floor") {
      sdat <- c(make_stan_data(ds), stan_priors(gq = 1L))   # gq=1 for p_event
      fit <- mod_int$sample(data = sdat, chains = CFG$chains,
        parallel_chains = CFG$parallel_chains, iter_warmup = CFG$iter_warmup,
        iter_sampling = CFG$iter_sampling, adapt_delta = CFG$adapt_delta,
        max_treedepth = CFG$max_treedepth, refresh = 0,
        show_messages = FALSE, show_exceptions = FALSE)
      dr <- fit$draws(variables = "p_event", format = "draws_matrix")
      pid <- sdat$pid_int
      ## KNOWN DEFECT, fixed here for future runs; the results in Table 12 were
      ## produced by the plug-in version below.
      ##   plug-in : pe <- colMeans(dr); 1 - prod(1 - pe[pid == j])
      ## That combines POSTERIOR MEAN hazards and so ignores the posterior
      ## dependence between a patient's intervals induced by the shared random
      ## effects. Because those hazards are positively dependent within a
      ## patient, E[prod(1-p)] >= prod(E[1-p]), so the plug-in OVER-states the
      ## predicted probability. The correct quantity is the posterior mean of
      ## the patient-level probability: form it per draw, then average.
      idx <- split(seq_along(pid), pid)
      pred <- vapply(idx, function(k) {
        sub <- dr[, k, drop = FALSE]                 # draws x intervals for this patient
        mean(1 - exp(rowSums(log1p(-pmin(sub, 1 - 1e-12)))))
      }, numeric(1))
      pred <- unname(pred[order(as.integer(names(idx)))])
    } else {
      sdat <- make_thr_data(ds, pat)
      fit <- mod_thr$sample(data = sdat, chains = CFG$chains,
        parallel_chains = CFG$parallel_chains, iter_warmup = CFG$iter_warmup,
        iter_sampling = CFG$iter_sampling, adapt_delta = CFG$adapt_delta,
        max_treedepth = CFG$max_treedepth, refresh = 0,
        show_messages = FALSE, show_exceptions = FALSE)
      pred <- colMeans(fit$draws(variables = "pDMR_end", format = "draws_matrix"))
    }

    dg <- fit$diagnostic_summary(quiet = TRUE)
    m  <- calib(pred, pat$delta)
    cbind(task_id = tk$task_id, cell_id = tk$cell_id, model = tk$model, n = tk$n,
          informative = tk$informative, rep = tk$rep, dgm_tag = dgm_tag(), m,
          ndiv = sum(dg$num_divergent), ebfmi = min(dg$ebfmi))
  }, error = function(e) data.frame(
      task_id = tk$task_id, cell_id = tk$cell_id, model = tk$model, n = tk$n,
      informative = tk$informative, rep = tk$rep, dgm_tag = dgm_tag(),
      brier = NA, error_msg = conditionMessage(e)))
  saveRDS(out, f); ndone <- ndone + 1L
  if (ndone %% 5 == 0) message(sprintf("  ...%d fits (%.1f h)", ndone,
      as.numeric(difftime(Sys.time(), start, units = "hours"))))
}
message(sprintf("Shard %d: %d new fits.", SHARD_ID, ndone))

## ---- aggregate --------------------------------------------------------------
if (SHARD_ID == 0L) {
  fs <- list.files(CFG$ckpt_dir, pattern = "\\.rds$", full.names = TRUE)
  if (length(fs)) {
    R <- dplyr::bind_rows(lapply(fs, readRDS)); R <- R[!is.na(R$brier), ]
    write.csv(R, file.path(CFG$out_dir, "calibration_raw.csv"), row.names = FALSE)
    ag <- do.call(rbind, lapply(split(R, R$cell_id), function(d) {
      k <- nrow(d)
      data.frame(cell_id = d$cell_id[1], model = d$model[1], n = d$n[1],
                 informative = d$informative[1], nrep = k,
                 brier = mean(d$brier), cal_int = mean(d$cal_int, na.rm = TRUE),
                 cal_slope = mean(d$cal_slope, na.rm = TRUE),
                 slope_mcse = sd(d$cal_slope, na.rm = TRUE)/sqrt(k),
                 mean_pred = mean(d$mean_pred), obs_rate = mean(d$obs_rate),
                 pct_with_divergences = mean(d$ndiv > 0),
                 mean_ndiv = mean(d$ndiv), row.names = NULL) }))
    write.csv(ag, file.path(CFG$out_dir, "calibration_summary.csv"), row.names = FALSE)
    print(ag, row.names = FALSE, digits = 3)
    message("\n-> calibration_summary.csv. Note pct_with_divergences for the threshold arm.")
  }
}
